name: power_file_view
description: A powerful file view widget, support a variety of file types, such as Doc Eexcl PPT TXT PDF and so on, Android is implemented by Tencent X5, iOS is implemented by WKWebView.
version: 1.0.1
homepage: https://github.com/vvkeep/flutter_power_file_view

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.0
  file_picker: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: cn.vvkeep.power_file_view
        pluginClass: PowerFileViewPlugin
      ios:
        pluginClass: PowerFileViewPlugin
